name: Get the NRFI stats
on: 
  workflow_dispatch: # This makes it so can manually trigger the workflow(optional)
  push:
    paths:
      - 'NRFI_STATS.py' # github can be trigger by a change to any file in to repo...
      - '.github/workflows/a.yml' #...including the workflow itself by specifying its path
 

permissions: write-all

  
jobs:
  Set-up-env-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  #REpository and file need to be checked out when workflow runs files within the repo
        uses: actions/checkout@v2
      - name: Checkout relevant files  
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            NRFI_STATS.py
          sparse-checkout-cone-mode: false
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.9'
          #Since the localphat from checking out the repo and the python needs was set up in the other job and not in the one with the run script it would not work here so need to 
          #make it so both run in the same job
      - name: Run script
        #Inside run: use same exact things as would on command line
        run: |
            pip install --upgrade pip
            pip install requests
            pip install bs4
            pip install numpy
            pip install matlab
            pip install pandas
            pip install datetime
            pip install selenium
            pip install matplotlib
            python NRFI_STATS.py
